config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :questions do
    resources :answers, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  get "/sign_out", to: "sessions#destroy"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, length: { minimum:  50 }
  validates :description, :question_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, length: { minimum: 40 }
  validates :description, length: { minimum: 150 }
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_or_create_by(uid: auth_hash[:uid], provider: auth_hash[:provider], username: auth_hash[:info][:email], avatar_url: auth_hash[:info][:image])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)

      if @answer.save
        redirect_to question_path(@question)
      else
        @answers = @question.answers
        render 'questions/show'
      end

  end

private
    def answer_params
      params.require(:answer).permit(:description)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :user_signed_in?, :current_user, :same_user?

  protected
  def find_or_create_from_auth_hash(auth_hash)
    User.find_or_create_by(uid: auth_hash[:uid], provider: auth_hash[:provider], username: auth_hash[:info][:email], avatar_url: auth_hash[:info][:image])
  end

  def user_signed_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def set_current_user(user)
    @current_user = user
  end

  def same_user?(user)
    user.user_id == current_user.id
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = 'You need to sign in if you want to do that!'

      redirect_to root_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(created_at: :desc)
    @answer = Answer.new
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question}
      else
        format.html { render action: 'new' }
      end
    end

  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end

  end

  def destroy
    @question = Question.find(params[:id])

    @question.destroy

    redirect_to questions_path
  end


private
    def question_params
      params.require(:question).permit(:title, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    set_current_user(@user)
    flash[:notice] = "YAY"

    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil

    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new

    Redcarpet::Markdown.new(renderer).render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% if user_signed_in? %>
      <p><img style= "border-radius: 60px; width: 60px" src="<%= current_user.avatar_url %>">
      <%= link_to 'Sign Out', "/sign_out" %></p>
    <% else %>
      <li><%= link_to 'Log in with Facebook', '/auth/facebook' %></li>
    <% end %>

<%= yield %>

<br />
<%= link_to 'Index', controller: 'welcome' %>
</body>
</html>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>
  <% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited
      this question from being saved:</h2>
    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: "50x10" %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "60x12" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', questions_path %>
<br />

app/views/questions/index.html.erb
<h1>Questions</h1>

  <ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to question.title, question_path(question) %>
    </li>
  <%end%>
  </ul>



<br />
<%= link_to 'Pose New Question', new_question_path %>
<br />

app/views/questions/new.html.erb
<h1>Pose a question</h1>

<%= form_for @question, url: {action: "create"}, html: {class: "input_form"} do |f| %>

  <% if @question.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited
      this question from being posed:</h2>
    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :description %><br />
  <%= f.text_area :description, size: "60x12" %>
  </p>

  <p>
  <%= f.submit "Create" %>
  </p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= markdown(@question.description) %></p>

<%= link_to 'Edit', edit_question_path %>

<%= link_to 'Delete', [@question],
            method: :delete,
            data: { confirm: 'Are you sure?' } %>



<h3>Answers</h3>

  <ul>
    <% @answers.each do |answer| %>
    <li>
    <%= answer.description %>
    </li>
    <%end%>
  </ul>





<h3>Submit Answer</h3>
<%= form_for [@question, @answer], html: {class: "input_form"} do |f| %>

  <% if @answer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited
      this answer from being posted:</h2>
    <ul>
    <% @answer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  <%= f.label :answer %><br />
  <%= f.text_area :description, size: "60x12" %>
  </p>

  <p>
  <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to "Back", questions_path %>
<br />

app/views/welcome/index.html.erb
<h1>Welcome to Rescue Mission</h1>

<%= link_to "Questions", questions_path %>
<br />